blueprint:
  domain: automation
  name: Dimmer Switch Mirror
  description: >
    Keep two dimmable lights in sync — when either one changes,
    the other automatically mirrors its on/off state and brightness.

  input:
    light_a:
      name: First Light
      description: The first dimmable light to mirror
      selector:
        entity:
          domain: light
    light_b:
      name: Second Light
      description: The second dimmable light to mirror
      selector:
        entity:
          domain: light

mode: queued
max: 2

trigger:
  - platform: state
    entity_id: !input light_a
  - platform: state
    entity_id: !input light_b

variables:
  light_a: !input light_a
  light_b: !input light_b

action:
  - variables:
      source_entity: "{{ trigger.entity_id }}"
      target_entity: >
        {% if trigger.entity_id == light_a %}
          {{ light_b }}
        {% else %}
          {{ light_a }}
        {% endif %}
      source_state: "{{ trigger.to_state.state }}"
      brightness: "{{ trigger.to_state.attributes.brightness | default(255) }}"

  - choose:
      # Light turned ON
      - conditions:
          - condition: template
            value_template: "{{ source_state == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ target_entity }}"
            data:
              brightness: "{{ brightness }}"
      # Light turned OFF
      - conditions:
          - condition: template
            value_template: "{{ source_state == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ target_entity }}"
