blueprint:
  name: Lutron Pico Paddle - Light/Switch
  description: |
    This automation allows for the control of one or more light or switch entities by a Lutron 2 Button Pico (PJ2-2B-GXX-X01).

  domain: automation

  input:
    pico_remote:
      name: Pico Remote
      description: "Select the pico remote to configure:"
      selector:
        device:
          filter:
            model: PJ2-1P-GXX (PaddleSwitchPico)
    entity:
      name: Entity(ies)
      description: "Light or switch entity to control."
      selector:
        entity:
          filter:
            domain:
              - light
              - switch
          multiple: true

trigger:
  - trigger: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: "Button 0"
    id: on_pressed

  - trigger: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: "Button 2"
    id: off_pressed

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: on_pressed
        sequence:
          - action: homeassistant.turn_on
            target:
              entity_id: !input entity
      - conditions:
          - condition: trigger
            id: off_pressed
        sequence:
          - action: homeassistant.turn_off
            target:
              entity_id: !input entity
    default: []

mode: single
