blueprint:
  domain: automation
  name: Lutron Pico Paddle - Light with Brightness Control (Debug)
  description: |
    Debug version with logging to trace Pico button press logic.

  input:
    pico:
      name: Pico Remote
      selector:
        device:
          integration: lutron_caseta
    entity:
      name: Light Entity(ies)
      selector:
        entity:
          filter:
            domain: light
          multiple: true
    step:
      name: Brightness Step Percentage
      default: 10
      selector:
        number:
          min: 1
          max: 25
          unit_of_measurement: percent
    hold:
      name: Hold Time
      default: 500
      selector:
        number:
          min: 100
          max: 1000
          unit_of_measurement: milliseconds
    transition_on:
      name: Transition On
      default: 0
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: seconds
    transition_off:
      name: Transition Off
      default: 0
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: seconds

variables:
  step_pct: !input step
  hold_time: !input hold

trigger:
  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: "on"
    id: on_pressed

  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: "off"
    id: off_pressed

action:
  - service: system_log.write
    data:
      level: info
      logger: blueprint.pico_dimmer
      message: "Automation started."

  - choose:
      - conditions:
          - condition: trigger
            id: on_pressed
        sequence:
          - service: system_log.write
            data:
              level: info
              logger: blueprint.pico_dimmer
              message: "ON button pressed — waiting for release..."
          - wait_for_trigger:
              - trigger: device
                device_id: !input pico
                domain: lutron_caseta
                type: release
                subtype: "on"
            timeout:
              milliseconds: "{{ hold_time }}"
            continue_on_timeout: true
          - if:
              - "{{ wait.remaining > 0 }}"
            then:
              - service: system_log.write
                data:
                  level: info
                  logger: blueprint.pico_dimmer
                  message: "Short ON press detected (remaining {{ wait.remaining }}s) — turning light on."
              - action: light.turn_on
                target:
                  entity_id: !input entity
                data:
                  brightness_pct: 100
                  transition: !input transition_on
            else:
              - service: system_log.write
                data:
                  level: info
                  logger: blueprint.pico_dimmer
                  message: "Long ON press detected — beginning brightness increase loop."
              - repeat:
                  sequence:
                    - action: light.turn_on
                      data:
                        brightness_step_pct: "{{ step_pct }}"
                      target:
                        entity_id: !input entity
                      continue_on_error: true
                    - service: system_log.write
                      data:
                        level: debug
                        logger: blueprint.pico_dimmer
                        message: "Stepped brightness up by {{ step_pct }}%"
                    - wait_for_trigger:
                        - trigger: device
                          device_id: !input pico
                          domain: lutron_caseta
                          type: release
                          subtype: "on"
                      timeout:
                        milliseconds: "{{ hold_time }}"
                      continue_on_timeout: true
                    - if:
                        - "{{ wait.remaining > 0 }}"
                      then:
                        - service: system_log.write
                          data:
                            level: info
                            logger: blueprint.pico_dimmer
                            message: "Released ON button — stopping brightness loop."
                        - stop:
                    - delay: 0.1
                  until:
                    - condition: numeric_state
                      entity_id: !input entity
                      attribute: brightness
                      above: 254

      - conditions:
          - condition: trigger
            id: off_pressed
        sequence:
          - service: system_log.write
            data:
              level: info
              logger: blueprint.pico_dimmer
              message: "OFF button pressed — waiting for release..."
          - wait_for_trigger:
              - trigger: device
                device_id: !input pico
                domain: lutron_caseta
                type: release
                subtype: "off"
            timeout:
              milliseconds: "{{ hold_time }}"
            continue_on_timeout: true
          - if:
              - "{{ wait.remaining > 0 }}"
            then:
              - service: system_log.write
                data:
                  level: info
                  logger: blueprint.pico_dimmer
                  message: "Short OFF press detected — turning light off."
              - action: light.turn_off
                target:
                  entity_id: !input entity
                data:
                  transition: !input transition_off
            else:
              - service: system_log.write
                data:
                  level: info
                  logger: blueprint.pico_dimmer
                  message: "Long OFF press detected — beginning brightness decrease loop."
              - repeat:
                  sequence:
                    - action: light.turn_on
                      data:
                        brightness_step_pct: "{{ step_pct * -1 }}"
                      target:
                        entity_id: !input entity
                      continue_on_error: true
                    - service: system_log.write
                      data:
                        level: debug
                        logger: blueprint.pico_dimmer
                        message: "Stepped brightness down by {{ step_pct }}%"
                    - wait_for_trigger:
                        - trigger: device
                          device_id: !input pico
                          domain: lutron_caseta
                          type: release
                          subtype: "off"
                      timeout:
                        milliseconds: "{{ hold_time }}"
                      continue_on_timeout: true
                    - if:
                        - "{{ wait.remaining > 0 }}"
                      then:
                        - service: system_log.write
                          data:
                            level: info
                            logger: blueprint.pico_dimmer
                            message: "Released OFF button — stopping brightness loop."
                        - stop:
                    - delay: 0.1
                  until:
                    - condition: numeric_state
                      entity_id: !input entity
                      attribute: brightness
                      below: 1

mode: single
