blueprint:
  domain: automation
  source_url: https://gist.github.com/cymone-smart/9814a750a0d0cfb196fa1fa7ae3630bb

  name: Lutron Pico 5 Button - Media Player Entity Control
  description: >-
    This blueprint allows for the association of a Lutron Pico 5 Button (model PJ2-3BRL-GXX-X01) remote with a media player entity. It is designed to simulate the operation of a standard Lutron Caseta audio pico including the press and hold functionality for the raise/lower buttons. It allows for     the control over the volume step percentage and the assignment of any
    action to the middle button.

  input:
    pico:
      name: Pico Device
      description: "Pico remote to associate with media player entity."
      selector:
        device:
          filter:
            model: PJ2-3BRL-GXX-X01 (Pico3ButtonRaiseLower)
    entity:
      name: Media Player Entity(ies)
      description: "Media Player entity to control."
      selector:
        entity:
          filter:
            domain: media_player
          multiple: true
    step:
      name: Volume Step Percentage
      description: "The percentage of volume to which the media player is changed when the RAISE/LOWER buttons are pressed and held."
      default: 10
      selector:
        number:
          min: 1
          max: 33
          unit_of_measurement: percentage

    speed:
      name: Volume Transition Speed
      description: "The rate of speed in milliseconds at which the brightness of the media_player entity will be changed."
      default: 500
      selector:
        number:
          min: 100
          max: 2000
          unit_of_measurement: milliseconds

    middle_button_action:
      name: Middle (Favorite) Button Override
      description: "Action(s) to execute when MIDDLE button is pressed. If left blank, no action will be taken."
      selector:
        action: {}
      default:

trigger:
  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: "on"
    id: on_pressed
  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: raise
    id: up_pressed
  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: stop
    id: stop_pressed
  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: lower
    id: down_pressed
  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: "off"
    id: off_pressed

variables:
  press_duration: 0.45
  middle_button_action: !input middle_button_action

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: on_pressed
        sequence:
          - action: media_player.media_play_pause
            data: {}
            target:
              entity_id: !input entity
      - conditions:
          - condition: trigger
            id: up_pressed
        sequence:
          - repeat:
              sequence:
                - action: media_player.volume_up
                  target:
                    entity_id: !input entity
                  continue_on_error: true
                - wait_for_trigger:
                    - trigger: device
                      device_id: !input pico
                      domain: lutron_caseta
                      type: release
                      subtype: raise
                  timeout: "{{ press_duration }}"
                  continue_on_timeout: true
                - if:
                    - "{{ wait.remaining > 0 }}"
                  then:
                    - stop:
              until:
                - condition: numeric_state
                  entity_id: !input entity
                  attribute: volume_level
                  above: 0.99
      - conditions:
          - condition: trigger
            id: stop_pressed
        sequence:
          - choose:
              - conditions: "{{ middle_button_action is not none and middle_button_action | length > 0 }}"
                sequence: !input middle_button_action
            default: []
      - conditions:
          - condition: trigger
            id: down_pressed
        sequence:
          - repeat:
              sequence:
                - action: media_player.volume_down
                  data: {}
                  target:
                    entity_id: !input entity
                  continue_on_error: true
                - wait_for_trigger:
                    - trigger: device
                      device_id: !input pico
                      domain: lutron_caseta
                      type: release
                      subtype: lower
                  timeout: "{{ press_duration }}"
                  continue_on_timeout: true
                - if:
                    - "{{ wait.remaining > 0 }}"
                  then:
                    - stop:
              until:
                - condition: numeric_state
                  entity_id: !input entity
                  attribute: volume_level
                  below: 0.01
      - conditions:
          - condition: trigger
            id: off_pressed
        sequence:
          - action: media_player.media_next_track
            data: {}
            target:
              entity_id: !input entity

mode: restart
