blueprint:
  domain: automation
  source_url: https://gist.github.com/cymone-smart/9814a750a0d0cfb196fa1fa7ae3630bb

  name: Lutron Pico 5 Button - Color Light Control
  description: "This blueprint allows for the association of a Lutron Pico 5 Button (model PJ2-3BRL-GXX-X01) remote with a light entity. It is designed to simulate the operation of a standard Lutron Caseta wall dimmer including the press and hold functionality for the raise/lower buttons. It allows for the control over the brightness step percentage and transition speed and the assignment of any action to the middle button."

  input:
    pico:
      name: Pico Device
      description: "Pico remote to associate with light entity."
      selector:
        device:
          filter:
            model: PJ2-3BRL-GXX-X01 (Pico3ButtonRaiseLower)
    light_entity:
      name: Light Entity(ies)
      description: "Light entity to control."
      selector:
        entity:
          filter:
            domain: light
          multiple: true
    phase_entity:
      name: Phase Entity
      description: "Phase entity to store last phase."
      selector:
        entity:
          filter:
            domain: input_number

trigger:
  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: "on"
    id: on_pressed
  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: raise
    id: raise_pressed
  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: stop
    id: stop_pressed
  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: lower
    id: lower_pressed
  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: "off"
    id: off_pressed

variables:
  press: 0.4
  step: 10

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: on_pressed
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              brightness_pct: 100

      - conditions:
          - condition: trigger
            id: raise_pressed
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  data:
                    brightness_step_pct: "{{ step }}"
                  target:
                    entity_id: !input light_entity
                  continue_on_error: true
                - wait_for_trigger:
                    - trigger: device
                      device_id: !input pico
                      domain: lutron_caseta
                      type: release
                      subtype: raise
                  timeout: "{{ press }}"
                  continue_on_timeout: true
                - if:
                    - "{{ wait.remaining > 0 }}"
                  then:
                    - stop:
              until:
                - condition: numeric_state
                  entity_id: !input light_entity
                  attribute: brightness
                  above: 254

      - conditions:
          - condition: trigger
            id: stop_pressed
        sequence:
          - variables:
              phase_entity: !input phase_entity
              phases:
                0: { color_temp: 357 }
                1: { color_temp: 250 }
                2: { color_name: "red" }
                3: { color_name: "magenta" }
                4: { color_name: "blue" }
                5: { color_name: "cyan" }
                6: { color_name: "green" }
              entity_test: !input light_entity
              phase: >
                {% set phase_value = states(phase_entity) | int(default=0) %}
                {% set next_phase = phase_value + 1 %}
                {{ 0 if next_phase not in phases else next_phase }}
          - action: light.turn_on
            target:
              entity_id: !input light_entity
            data: "{{ phases[phase] }}"
          - action: input_number.set_value
            target:
              entity_id: !input phase_entity
            data:
              value: "{{ phase }}"
          - delay:
              milliseconds: 500

      - conditions:
          - condition: trigger
            id: lower_pressed
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  data:
                    brightness_step_pct: "{{ -step }}"
                  target:
                    entity_id: !input light_entity
                  continue_on_error: true
                - wait_for_trigger:
                    - trigger: device
                      device_id: !input pico
                      domain: lutron_caseta
                      type: release
                      subtype: lower
                  timeout: "{{ press }}"
                  continue_on_timeout: true
                - if:
                    - "{{ wait.remaining > 0 }}"
                  then:
                    - stop:
              until:
                - condition: numeric_state
                  entity_id: !input light_entity
                  attribute: brightness
                  below: 1

      - conditions:
          - condition: trigger
            id: off_pressed
        sequence:
          - action: light.turn_off
            target:
              entity_id: !input light_entity

mode: restart
