blueprint:
  domain: automation

  name: Lutron Pico Paddle - Light with Brightness Control
  description: |
    This automation allows for controlling one or more light entities with a Lutron Paddle Pico (PJ2-1P-GXX).
    A short press will toggle the light on/off, while a long press will gradually adjust brightness.

  input:
    pico:
      name: Pico Remote
      description: "Select the Pico remote to configure:"
      selector:
        device:
          integration: lutron_caseta

    entity:
      name: Light Entity(ies)
      description: "Light entity to control."
      selector:
        target:
          entity:
            domain: light
          multiple: true

trigger:
  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: "on"
    id: on_pressed

  - trigger: device
    device_id: !input pico
    domain: lutron_caseta
    type: press
    subtype: "off"
    id: off_pressed

variables:
  press_duration: 0.5
  step_pct: 10

action:
  - choose:
      - conditions:
          - condition: trigger
            id: on_pressed
        sequence:
          - wait_for_trigger:
              - trigger: device
                device_id: !input pico
                domain: lutron_caseta
                type: release
                subtype: "on"
            timeout: "{{ press_duration }}"
            continue_on_timeout: true
          - if:
              - "{{ wait.remaining > 0 }}"
            then:
              - action: light.turn_on
                target:
                  entity_id: !input entity
                data:
                  brightness: 255
            else:
              - repeat:
                  sequence:
                    - action: light.turn_on
                      data:
                        brightness_step_pct: "{{ step_pct }}"
                      target:
                        entity_id: !input entity
                      continue_on_error: true
                    - wait_for_trigger:
                        - trigger: device
                          device_id: !input pico
                          domain: lutron_caseta
                          type: release
                          subtype: "on"
                      timeout: "{{ press_duration }}"
                      continue_on_timeout: true
                    - if:
                        - "{{ wait.remaining > 0 }}"
                      then:
                        - stop:
                  until:
                    - condition: numeric_state
                      entity_id: !input entity
                      attribute: brightness
                      above: 254
      - conditions:
          - condition: trigger
            id: off_pressed
        sequence:
          - wait_for_trigger:
              - trigger: device
                device_id: !input pico
                domain: lutron_caseta
                type: release
                subtype: "off"
            timeout: "{{ press_duration }}"
            continue_on_timeout: true
          - if:
              - "{{ wait.remaining > 0 }}"
            then:
              - action: light.turn_off
                target:
                  entity_id: !input entity
            else:
              - repeat:
                  sequence:
                    - action: light.turn_on
                      data:
                        brightness_step_pct: "{{ -step_pct }}"
                      target:
                        entity_id: !input entity
                      continue_on_error: true
                    - wait_for_trigger:
                        - trigger: device
                          device_id: !input pico
                          domain: lutron_caseta
                          type: release
                          subtype: "off"
                      timeout: "{{ press_duration }}"
                      continue_on_timeout: true
                    - if:
                        - "{{ wait.remaining > 0 }}"
                      then:
                        - stop:
                  until:
                    - condition: numeric_state
                      entity_id: !input entity
                      attribute: brightness
                      below: 1

mode: restart
