blueprint:
  domain: automation

  name: Phase Activated Actions
  description: Time Activated Actions

  input:
    phase:
      name: Phase
      description: The phase that will trigger this automation.
      selector:
        select:
          options:
            - Morning
            - Day
            - Evening
            - Night
    modes:
      name: Modes
      description: The modes during which this automation will execute.
      selector:
        select:
          options:
            - Home
            - Away
            - Guest
            - Entertain
            - Vacation
          multiple: true
      default:
        - Home
        - Away
        - Vacation
    scenes:
      name: Scene(s)
      description: The scene(s) that will be activated.
      selector:
        entity:
          filter:
            domain: scene
          multiple: true
    scripts:
      name: Script(s)
      description: The scene(s) that will be activated.
      selector:
        entity:
          filter:
            domain: script
          multiple: true
    lights_on:
      name: Lights On
      description: The light entities that will be turned on.
      selector:
        entity:
          filter:
            domain: light
          multiple: true
    lights_level:
      name: Light Brightness
      description: The level of brightness to set the lights when they are turned on.
      default: 0
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    lights_kelvin:
      name: Light Temperature
      description: The color temperature (in Kelvin) to set the lights when they are turned on.
      default: 2800
      selector:
        number:
          min: 2000
          max: 6535
          unit_of_measurement: "kelvin"
    lights_off:
      name: Lights Off
      description: The light entities that will be turned off.
      selector:
        entity:
          filter:
            domain: light
          multiple: true
    fans_on:
      name: Fans On
      description: The fan entities that will be turned on.
      selector:
        entity:
          filter:
            domain: fan
          multiple: true
    fans_level:
      name: Fan Speed
      description: The level of speed to set the fans when they are turned on.
      default: 0
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    fans_off:
      name: Fans Off
      description: The fan entities that will be turned off.
      selector:
        entity:
          filter:
            domain: fan
          multiple: true
    shades_open:
      name: Shades Open
      description: The shade entities that will be opened.
      selector:
        entity:
          filter:
            domain: cover
          multiple: true
    shades_position:
      name: Shades Position
      description: The position to set the shadess when they are opened on.
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
      default: 100
    shades_close:
      name: Shades Close
      description: The shade entities that will be closed.
      selector:
        entity:
          filter:
            domain: cover
          multiple: true
    switches_on:
      name: Switches On
      description: The switch entities that will be turned on.
      selector:
        entity:
          filter:
            domain: switch
          multiple: true
    switches_off:
      name: Switches Off
      description: The switch entities that will be turned off.
      selector:
        entity:
          filter:
            domain: switch
          multiple: true
    garages:
      name: Garage Doors
      description: The garage door entities that will be closed.
      selector:
        entity:
          filter:
            domain: cover
    locks:
      name: Door Locks
      description: The locks entities that will be locked.
      selector:
        entity:
          filter:
            domain: lock
          multiple: true
    media_players:
      name: TVs
      description: The TVs entities that will be turned off.
      selector:
        entity:
          filter:
            domain: media_player
          multiple: true
    actions:
      name: General Actions
      description: The actions to execute.
      selector:
        action:

variables:
  modes: !input modes
  scenes: !input scenes
  scenes_list: "{{ expand(scenes) | rejectattr('state', 'in', ['unavailable', 'unknown']) | map(attribute='entity_id') | list }}"
  scripts: !input scripts
  scripts_list: "{{ expand(scripts) | rejectattr('state', 'in', ['unavailable', 'unknown']) | map(attribute='entity_id') | list }}"
  lights_on: !input lights_on
  lights_on_list: "{{ expand(lights_on) | rejectattr('state', 'in', ['unavailable', 'unknown']) | map(attribute='entity_id') | list }}"
  lights_off: !input lights_off
  lights_off_list: "{{ expand(lights_off) | rejectattr('state', 'in', ['unavailable', 'unknown']) | map(attribute='entity_id') | list }}"
  fans_on: !input fans_on
  fans_on_list: "{{ expand(fans_on) | rejectattr('state', 'in', ['unavailable', 'unknown']) | map(attribute='entity_id') | list }}"
  fans_off: !input fans_off
  fans_off_list: "{{ expand(fans_off) | rejectattr('state', 'in', ['unavailable', 'unknown']) | map(attribute='entity_id') | list }}"
  shades_open: !input shades_open
  shades_open_list: "{{ expand(shades_open) | rejectattr('state', 'in', ['unavailable', 'unknown']) | map(attribute='entity_id') | list }}"
  shades_close: !input shades_close
  shades_close_list: "{{ expand(shades_close) | rejectattr('state', 'in', ['unavailable', 'unknown']) | map(attribute='entity_id') | list }}"
  shades_position: !input shades_position
  switches_on: !input switches_on
  switches_on_list: "{{ expand(switches_on) | rejectattr('state', 'in', ['unavailable', 'unknown']) | map(attribute='entity_id') | list }}"
  switches_off: !input switches_off
  switches_off_list: "{{ expand(switches_off) | rejectattr('state', 'in', ['unavailable', 'unknown']) | map(attribute='entity_id') | list }}"
  garages: !input garages
  garages_list: "{{ expand(garages) | rejectattr('state', 'in', ['unavailable', 'unknown']) | map(attribute='entity_id') | list }}"
  locks: !input locks
  locks_list: "{{ expand(locks) | rejectattr('state', 'in', ['unavailable', 'unknown']) | map(attribute='entity_id') | list }}"
  media_players: !input media_players
  media_players_list: "{{ expand(media_players) | rejectattr('state', 'in', ['unavailable', 'unknown']) | map(attribute='entity_id') | list }}"
  actions: !input actions

trigger:
  - trigger: state
    entity_id: input_button.location_phase

condition:
  - condition: state
    entity_id: input_select.location_phase
    state: !input phase
  - condition: template
    value_template: "{{ states('input_select.location_mode') in modes }}"

action:
  # Scenes
  - if:
      - condition: template
        value_template: "{{ scenes_list | length > 0 }}"
    then:
      - action: scene.turn_on
        data:
          transition: 1
        target:
          entity_id: "{{ scenes_list }}"
        continue_on_error: true
  # Scripts
  - if:
      - condition: template
        value_template: "{{ scripts_list | length > 0 }}"
    then:
      - action: script.turn_on
        target:
          entity_id: "{{ scripts_list }}"
        continue_on_error: true
  # Lights
  - if:
      - condition: template
        value_template: "{{ lights_on_list | length > 0 }}"
    then:
      - action: light.turn_on
        data:
          brightness_pct: !input lights_level
          color_temp_kelvin: !input lights_kelvin
        target:
          entity_id: "{{ lights_on_list }}"
        continue_on_error: true
  - if:
      - condition: template
        value_template: "{{ lights_off_list | length > 0 }}"
    then:
      - action: light.turn_off
        target:
          entity_id: "{{ lights_off_list }}"
        continue_on_error: true
  # Fans
  - if:
      - condition: template
        value_template: "{{ fans_on_list | length > 0 }}"
    then:
      - action: fan.turn_on
        data:
          percentage: !input fans_level
        target:
          entity_id: "{{ fans_on_list }}"
        continue_on_error: true
  - if:
      - condition: template
        value_template: "{{ fans_off_list | length > 0 }}"
    then:
      - action: fan.turn_off
        target:
          entity_id: "{{ fans_off_list }}"
        continue_on_error: true
  # Shades
  - if:
      - condition: template
        value_template: "{{ shades_open_list | length > 0 }}"
    then:
      - action: cover.set_cover_position
        data:
          position: "{{ shades_position }}"
        target:
          entity_id: "{{ shades_open_list }}"
        continue_on_error: true
  - if:
      - condition: template
        value_template: "{{ shades_close_list | length > 0 }}"
    then:
      - action: cover.close_cover
        target:
          entity_id: "{{ shades_close_list }}"
        continue_on_error: true
  # Switches
  - if:
      - condition: template
        value_template: "{{ switches_on_list | length > 0 }}"
    then:
      - action: switch.turn_on
        target:
          entity_id: "{{ switches_on_list }}"
        continue_on_error: true
  - if:
      - condition: template
        value_template: "{{ switches_off_list | length > 0 }}"
    then:
      - action: switch.turn_off
        target:
          entity_id: "{{ switches_off_list }}"
        continue_on_error: true
  # Garage Doors
  - if:
      - condition: template
        value_template: "{{ garages_list | length > 0 }}"
    then:
      - action: cover.close_cover
        target:
          entity_id: "{{ garages_list }}"
        continue_on_error: true
  # Door Locks
  - if:
      - condition: template
        value_template: "{{ locks_list | length > 0 }}"
    then:
      - action: lock.lock
        target:
          entity_id: "{{ locks_list }}"
        continue_on_error: true
  # Media Players
  - if:
      - condition: template
        value_template: "{{ media_players_list | length > 0 }}"
    then:
      - action: media_player.turn_off
        target:
          entity_id: "{{ media_players_list }}"
        continue_on_error: true
  # Actions
  - if:
      - condition: template
        value_template: "{{ actions is not none and actions | length > 0 }}"
    then:
      - sequence: !input actions

mode: single
