blueprint:
  domain: script

  name: Relay Pulse
  description: >
    Turns on a light or switch entity briefly to simulate a momentary press or pulse,
    then turns it off after a configurable duration.

  input:
    target_entity:
      name: Target Entity
      description: The switch or light entity to pulse
      selector:
        entity:
          domain:
            - light
            - switch

    pulse_duration:
      name: Pulse Duration
      description: How long the entity stays on before turning off (in seconds)
      default: 1
      selector:
        number:
          min: 0.1
          max: 10
          step: 0.1
          unit_of_measurement: seconds

sequence:
  - service: homeassistant.turn_on
    target:
      entity_id: !input target_entity

  - delay:
      seconds: !input pulse_duration

  - service: homeassistant.turn_off
    target:
      entity_id: !input target_entity
