blueprint:
  domain: automation

  name: Sensor Activated Actions
  description: |
    This automation triggers the execution of a set of actions based upon:
      - The state of one or more sensor entities
      - The current phase of the location

  input:
    sensor:
      name: Sensor(s)
      description: The sensor(s) that will trigger this automation.
      default: []
      selector:
        entity:
          filter:
            domain: binary_sensor
          multiple: true

    sensor_clear:
      name: Sensor Clear Time
      description: The time in seceonds that it takes for the sensor to clear. For a motion sensor, this is usually 60 seconds.
      default: 60
      selector:
        number:
          min: 0
          max: 360
          unit_of_measurement: seconds

    on_action_morning:
      name: Morning - Sensor On Actions
      description: Actions to execute when the sensor changes to the 'on' state.
      default:
      selector:
        action:
    duration_morning:
      name: Morning - Duration
      description: The time (in minutes) to wait before executing the Sensor Off Actions.
      default: 0
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: minutes
    off_action_morning:
      name: Morning - Sensor Off Actions
      description: The actions to execute when the sensor changes to the 'off' state.
      default:
      selector:
        action:

    on_action_day:
      name: Day - Sensor On Actions
      description: Actions to execute when the sensor changes to the 'on' state.
      default:
      selector:
        action:
    duration_day:
      name: Day - Duration
      description: The time (in minutes) to wait before executing the Sensor Off Actions.
      default: 0
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: minutes
    off_action_day:
      name: Day - Sensor Off Actions
      description: The actions to execute when the sensor changes to the 'off' state.
      default:
      selector:
        action:

    on_action_evening:
      name: Evening - Sensor On Actions
      description: Actions to execute when the sensor changes to the 'on' state.
      default:
      selector:
        action:
    duration_evening:
      name: Evening - Duration
      description: The time (in minutes) to wait before executing the Sensor Off Actions.
      default: 0
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: minutes
    off_action_evening:
      name: Evening - Sensor Off Actions
      description: The actions to execute when the sensor changes to the 'off' state.
      default:
      selector:
        action:

    on_action_night:
      name: Night - Sensor On Actions
      description: Actions to execute when the sensor changes to the 'on' state.
      default:
      selector:
        action:
    duration_night:
      name: Night - Duration
      description: The time (in minutes) to wait before executing the Sensor Off Actions.
      default: 0
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: minutes
    off_action_night:
      name: Night - Sensor Off Actions
      description: The actions to execute when the sensor changes to the 'off' state.
      default:
      selector:
        action:

variables:
  sensor_clear: !input sensor_clear
  phase: "{{ states('input_select.location_phase') }}"
  duration_list:
    Morning: !input duration_morning
    Day: !input duration_day
    Evening: !input duration_evening
    Night: !input duration_night
  duration: "{{ duration_list[phase] | default(0) }}"

trigger:
  - trigger: state
    entity_id: !input sensor
    to: "on"
    id: sensor_on
  - trigger: state
    entity_id: !input sensor
    to: "off"
    id: sensor_off

action:
  - choose:
      - conditions:
          - condition: trigger
            id: sensor_on
        sequence:
          - choose:
              - conditions: "{{ phase == 'Morning' }}"
                sequence: !input on_action_morning
              - conditions: "{{ phase == 'Day' }}"
                sequence: !input on_action_day
              - conditions: "{{ phase == 'Evening' }}"
                sequence: !input on_action_evening
              - conditions: "{{ phase == 'Night' }}"
                sequence: !input on_action_night
      - conditions:
          - condition: trigger
            id: sensor_off
        sequence:
          - delay:
              seconds: "{{ max(duration * 60 - sensor_clear, 0) }}"
          - choose:
              - conditions: "{{ phase == 'Morning' }}"
                sequence: !input off_action_morning
              - conditions: "{{ phase == 'Day' }}"
                sequence: !input off_action_day
              - conditions: "{{ phase == 'Evening' }}"
                sequence: !input off_action_evening
              - conditions: "{{ phase == 'Night' }}"
                sequence: !input off_action_night

mode: restart
