blueprint:
  domain: automation
  name: Sensor Activated Lights
  description: |
    This automation controls the state and brightness of one or more light entities based on:
      - The state of one or more sensor entities
      - The current phase of the location

    Notes: 
      - A duration of '0' prevents the light from turning on during that phase.
      - A duration of '99' keeps the light on indefinitely.
      - If a light does not support brightness control, 'Brightness' will be ignored.

  input:
    sensor:
      name: Sensor(s)
      description: The sensor(s) that will trigger this automation.
      selector:
        entity:
          filter:
            domain: binary_sensor
          multiple: true

    light:
      name: Light(s)
      description: The light entity(ies) which will be controlled.
      selector:
        entity:
          filter:
            domain: light
          multiple: true

    duration_morning:
      name: Morning - Duration
      description: Duration in minutes for which the lights will remain on.
      default: 15
      selector:
        number:
          min: 0
          max: 99
          unit_of_measurement: minutes
    brightness_morning:
      name: Morning - Brightness
      description: Brightness level of the lights.
      default: 75
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    duration_day:
      name: Day - Duration
      description: Duration in minutes for which the lights will remain on.
      default: 15
      selector:
        number:
          min: 0
          max: 99
          unit_of_measurement: minutes
    brightness_day:
      name: Day - Brightness
      description: Brightness level of the lights.
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    duration_evening:
      name: Evening - Duration
      description: Duration in minutes for which the lights will remain on.
      default: 15
      selector:
        number:
          min: 0
          max: 99
          unit_of_measurement: minutes
    brightness_evening:
      name: Evening - Brightness
      description: Brightness level of the lights.
      default: 75
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    duration_night:
      name: Night - Duration
      description: Duration in minutes for which the lights will remain on.
      default: 5
      selector:
        number:
          min: 0
          max: 99
          unit_of_measurement: minutes
    brightness_night:
      name: Night - Brightness
      description: Brightness level of the lights.
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

variables:
  phase: "{{ states('input_select.location_phase') }}"
  durations:
    Morning: !input duration_morning
    Day: !input duration_day
    Evening: !input duration_evening
    Night: !input duration_night
  brightness_levels:
    Morning: !input brightness_morning
    Day: !input brightness_day
    Evening: !input brightness_evening
    Night: !input brightness_night
  duration: "{{ durations[phase] | default(0) * 60 }}"
  brightness: "{{ brightness_levels[phase] | default(0) }}"

trigger:
  - platform: state
    entity_id: !input sensor
    to: "on"

condition:
  - condition: template
    value_template: "{{ duration > 0 }}"

action:
  - action: light.turn_on
    data:
      transition: 1
      brightness_pct: "{{ brightness }}"
    target:
      entity_id: !input light
  - if:
      - condition: template
        value_template: "{{ duration != 99 }}"
    then:
      - delay:
          seconds: "{{ duration }}"
      - if:
          - condition: state
            entity_id: !input sensor
            state: "on"
        then:
          - wait_for_trigger:
              - trigger: state
                entity_id: !input sensor
                to: "off"
      - action: light.turn_off
        data:
          transition: 2
        target:
          entity_id: !input light

mode: single
