blueprint:
  name: Two Switch Mirror
  description: >
    Keep two independent switches in sync — when either one changes,
    the other automatically mirrors its state.
  domain: automation
  input:
    switch_a:
      name: First Switch
      description: The first switch to mirror
      selector:
        entity:
          domain: switch
    switch_b:
      name: Second Switch
      description: The second switch to mirror
      selector:
        entity:
          domain: switch

mode: queued
max: 2

trigger:
  - platform: state
    entity_id: !input switch_a
  - platform: state
    entity_id: !input switch_b

action:
  - service: "switch.turn_{{ trigger.to_state.state }}"
    target:
      entity_id: >
        {% if trigger.entity_id == (switch_a | string) %}
          {{ switch_b }}
        {% else %}
          {{ switch_a }}
        {% endif %}
