blueprint:
  name: Time Phase Control
  description: Change the phase of the day based on time triggers, with minute offsets for sunrise and sunset.
  domain: automation
  input:
    morning:
      name: Morning
      description: "Offset for the sunrise time in minutes (e.g., '-30' for 30 minutes before sunrise, '15' for 15 minutes after)."
      default: 0
      selector:
        number:
          min: -999
          max: 999
          mode: box
    day:
      name: Day
      description: Time when it's considered day.
      default: "08:00:00"
      selector:
        time: {}
    evening:
      name: Evening
      description: "Offset for the sunset time in minutes (e.g., '-30' for 30 minutes before sunset, '15' for 15 minutes after)."
      default: 0
      selector:
        number:
          min: -999
          max: 999
          mode: box
    night:
      name: Night
      description: Time when it's considered night.
      default: "23:00:00"
      selector:
        time: {}

trigger:
  - trigger: sun
    event: sunrise
    offset: !input morning
    id: morning
  - trigger: time
    at: !input day
    id: day
  - trigger: sun
    event: sunset
    offset: !input evening
    id: evening
  - trigger: time
    at: !input night
    id: night

action:
  - choose:
      - conditions:
          - condition: trigger
            id: morning
        sequence:
          - action: input_select.select_option
            target:
              entity_id: input_select.location_phase
            data:
              option: Morning
      - conditions:
          - condition: trigger
            id: day
        sequence:
          - action: input_select.select_option
            target:
              entity_id: input_select.location_phase
            data:
              option: Day
      - conditions:
          - condition: trigger
            id: evening
        sequence:
          - action: input_select.select_option
            target:
              entity_id: input_select.location_phase
            data:
              option: Evening
      - conditions:
          - condition: trigger
            id: night
          - condition: not
            conditions:
              - condition: state
                entity_id: input_select.location_mode
                state: Entertain
        sequence:
          - action: input_select.select_option
            target:
              entity_id: input_select.location_phase
            data:
              option: Night

  - action: input_button.press
    target:
      entity_id: input_button.location_phase

mode: single
