blueprint:
  domain: automation
  name: Time Activating Scenes
  description: |
    Activate a scene or list of scenes at a specific time or offset to sunrise/sunset.
    Includes a transition time setting and day of week selection.

  input:
    scene_list:
      name: Scenes to Activate
      description: A scene or list of scenes to activate
      default: []
      selector:
        entity:
          filter:
            domain: scene
          multiple: true

    transition:
      name: Transition Time (optional)
      description: Transition time in seconds for scene entities that support it
      default: 0
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
          step: 1
          mode: slider

    trigger_mode:
      name: Trigger Mode
      description: Choose how to trigger the automation
      selector:
        select:
          options:
            - time
            - sunrise
            - sunset

    trigger_time:
      name: Trigger Time (if mode is 'time')
      selector:
        time: {}

    offset:
      name: Offset (if mode is sunrise or sunset)
      description: Positive or negative offset in HH:MM format (e.g., -00:30 or 01:00)
      default: "00:00"
      selector:
        text:
          type: text

    start_date:
      name: Start Date (MM-DD)
      description: The beginning of the valid date range (month and day only)
      default: "01-01"
      selector:
        text:
          type: text

    end_date:
      name: End Date (MM-DD)
      description: The end of the valid date range (month and day only)
      default: "12-31"
      selector:
        text:
          type: text

    days_of_week:
      name: Days of Week
      description: Select the days of the week when the automation should run
      default:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      selector:
        select:
          multiple: true
          options:
            - label: Monday
              value: mon
            - label: Tuesday
              value: tue
            - label: Wednesday
              value: wed
            - label: Thursday
              value: thu
            - label: Friday
              value: fri
            - label: Saturday
              value: sat
            - label: Sunday
              value: sun

variables:
  start_date: !input start_date
  end_date: !input end_date
  trigger_mode: !input trigger_mode
  selected_days: !input days_of_week

trigger:
  - trigger: time
    at: !input trigger_time
    id: time
  - trigger: sun
    event: sunrise
    offset: !input offset
    id: sunrise
  - trigger: sun
    event: sunset
    offset: !input offset
    id: sunset

condition:
  - condition: template
    value_template: >
      {% if trigger.id == 'time' %}
        {{ trigger_mode == 'time' }}
      {% elif trigger.id == 'sunrise' %}
        {{ trigger_mode == 'sunrise' }}
      {% elif trigger.id == 'sunset' %}
        {{ trigger_mode == 'sunset' }}
      {% else %}
        false
      {% endif %}
  - condition: template
    value_template: >
      {% set today = now().strftime('%m-%d') %}
      {% if start_date <= end_date %}
        {{ start_date <= today <= end_date }}
      {% else %}
        {{ today >= start_date or today <= end_date }}
      {% endif %}
  - condition: template
    value_template: >
      {% set current_day = now().strftime('%a').lower()[:3] %}
      {{ current_day in selected_days }}

action:
  - action: scene.turn_on
    target:
      entity_id: !input scene_list
    data:
      transition: !input transition

mode: single
